package com.runningrace.model;

import lombok.Data;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;

@Data
@Entity
public class Race {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String name;
    private double distance; // Distance in kilometers

    @OneToMany(mappedBy = "race")
    @JsonManagedReference
    private List<Result> results; // Results associated with this race

    // Default constructor
    public Race() {
    }

    // Parameterized constructor
    public Race(String name, double distance) {
        this.name = name;
        this.distance = distance;
    }

    // Getters and setters, toString, equals, and hashCode methods are generated by Lombok

}