package com.runningrace.model;

import lombok.Data;
import jakarta.persistence.*;
import java.util.List;

@Data
@Entity
public class Race {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String name;
    private double distance; // Distance in kilometers

    @OneToMany(mappedBy = "race")
    private List<Result> results; // Results associated with this race

    // Default constructor
    public Race() {
    }

    // Parameterized constructor
    public Race(String name, double distance) {
        this.name = name;
        this.distance = distance;
    }

    // Getters and setters, toString, equals, and hashCode methods are generated by Lombok
}